### ISSUE TITLE
Homecoming refactor

### ISSUE THREAD

**Issue by Soreine** [Soreine/hyper-gwent#49]
Gwent: Homecoming, is the opportunity to relaunch this project with a better software design and better features.

I'm currently writing an Airtable to list ideas of features and implementation. https://airtable.com/shrutxx7zcKeS2ChW

**Comment by Soreine** [comment]
Here is the relevant info that we can find for a card in `gwent-data-release`.

```yaml
card:
  ingameId: 112109
  name: "Geralt von Riva"
  faction: "Neutral"
  strength: 3
  type: "Gold"
  cardType: "Unit"
  categories: ["Witcher"]
  info: "Deploy: Destroy an enemy with 8 or more power."
  infoRaw: "<keyword=deploy>Deploy</keyword>: Destroy an enemy with 8 or more power."
  loyalties: "Loyal"
  positions: ["Melee", "Ranged", "Siege"]
  provision: 10
  related: []
  released: true
  rarity: Legendary
  related: [
      '112404',
      '112403'
  ]
  variations:
    '11210300':
      art:
        high: https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Fv1.0.0.15-522%2F112103%2F11210300%2Fhigh.png?alt=media
        low: https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Fv1.0.0.15-522%2F112103%2F11210300%2Flow.png?alt=media
        medium: https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Fv1.0.0.15-522%2F112103%2F11210300%2Fmedium.png?alt=media
        original: https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Fv1.0.0.15-522%2F112103%2F11210300%2Foriginal.png?alt=media
        thumbnail: https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Fv1.0.0.15-522%2F112103%2F11210300%2Fthumbnail.png?alt=media
```
